# 1. Configuración SEO y Metadatos
seo:
  title: "Baby Shower"
  description: "¡Acompáñanos a celebrar la llegada de nuestro bebé! Confirma tu asistencia y mira la lista de regalos."
  url: "https://babyshower-coraline.vercel.app"
  image: favicon.ico

# 2. Información de los Padres
baby: 
  name: "Coraline"
  gender: "Girl"
parents:
  mom: "Sayreth"
  dad: "Fran"

# 3. Detalles del Evento
event:
  date: "Sábado, 7 de marzo"
  dateISO: "2026-03-07"
  time: "15:00 - 19:00"
  location:
    address: "Avenida Jerez 54, Nuevo Baztán"
    googleMapsUrl: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3040.3519259187888!2d-3.254783824206704!3d40.356720371449335!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd425b4e6be04a7b%3A0xde6ae6a394d1e72c!2sAv.%20Jerez%2C%2054%2C%2028514%20Nuevo%20Bazt%C3%A1n%2C%20Madrid!5e0!3m2!1ses-419!2ses!4v1762512114152!5m2!1ses-419!2ses

# 4. Configuración de Recordatorios
reminders:
  # Días antes del evento en los que se enviarán recordatorios por email
  # Ejemplo: [7, 1] enviará recordatorios 1 semana y 1 día antes
  days: [7, 1]
