import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className="flex flex-col w-full items-center gap-6 md:gap-8 py-4 md:py-8 px-4 md:px-64"
        style={{ color: "black", backgroundColor: "#f8f6f6" }}
      >
        <main className="flex flex-col w-full gap-3 md:gap-6">
          {children}
        </main>
        <hr className="w-full" style={{ color: "#efd4db" }} />
        <footer className="flex flex-col w-full items-center text-black/60">
          <small>¡Gracias por celebrar con nosotros!</small>
          <small>Con amor, Sayreth & Francisco</small>
        </footer>
      </body>
    </html>
  );
}
